// DOM references owned by the browser presentation layer.

const el = {
  stageTitle: document.querySelector("#stageTitle"),
  enemySide: document.querySelector("#enemySide"),
  heroHpBar: document.querySelector("#heroHpBar"),
  heroMpBar: document.querySelector("#heroMpBar"),
  heroVitals: document.querySelector("#heroVitals"),
  targetName: document.querySelector("#targetName"),
  soulRow: document.querySelector("#soulRow"),
  battleLog: document.querySelector("#battleLog"),
  hand: document.querySelector("#hand"),
  energyText: document.querySelector("#energyText"),
  deckText: document.querySelector("#deckText"),
  turnText: document.querySelector("#turnText"),
  endTurnButton: document.querySelector("#endTurnButton"),
  statsButton: document.querySelector("#statsButton"),
  restartButton: document.querySelector("#restartButton"),
  statsModal: document.querySelector("#statsModal"),
  closeStats: document.querySelector("#closeStats"),
  statsGrid: document.querySelector("#statsGrid"),
  equipmentList: document.querySelector("#equipmentList"),
  soulList: document.querySelector("#soulList"),
  extractModal: document.querySelector("#extractModal"),
  extractImage: document.querySelector("#extractImage"),
  extractText: document.querySelector("#extractText"),
  extractChance: document.querySelector("#extractChance"),
  confirmExtract: document.querySelector("#confirmExtract"),
  skipExtract: document.querySelector("#skipExtract"),
  resultModal: document.querySelector("#resultModal"),
  resultTitle: document.querySelector("#resultTitle"),
  resultText: document.querySelector("#resultText"),
  continueButton: document.querySelector("#continueButton"),
  lootModal: document.querySelector("#lootModal"),
  lootBody: document.querySelector("#lootBody"),
  equipLootButton: document.querySelector("#equipLootButton"),
  salvageLootButton: document.querySelector("#salvageLootButton"),
};
